### ISSUE TITLE
For Next Step -1

### ISSUE THREAD

**Issue by chunkypixel** [7800-devtools/7800basic#1]
When using  For/Next Step -1 the program freezes but interestingly For/Next Step -2 or better works no problem.

Find attached a sample application and compilation assembly

[fornext-example.zip](https://github.com/7800-devtools/7800basic/files/4290096/fornext-example.zip)

**Comment by msaarna** [comment]
Thanks for the report and sample code! I've updated master with the fix, and will be putting out a new RC shortly.
