### ISSUE TITLE
Plot Sprite Issue in 0.13 

### ISSUE THREAD

**Issue by peteym5** [7800-devtools/7800basic#2]
Plot Sprite Issue in 0.13 and possibly later. When sprites of height of 16 or more are put on screen, Bottom 8 pixels seem to be not positioned correctly. Can you please check what is going on. I tried several of your samples. Same issue. 

![image](https://user-images.githubusercontent.com/42674155/97113617-08adb380-16c2-11eb-982e-b0d19e1a1825.png)

**Comment by msaarna** [comment]
Is this in emulation, and if so, what emulator?

The sprite plotting routines were updated to be more efficient, and it broke in Prosystem and it's forks. Assuming this is the same issue, the code works correctly on real hardware, A7800, Mame, and JS7800.

**Comment by peteym5** [comment]
I tested on another emulator (Mame) and it works. I am phasing out usage of Prosystem. Prosystem has not been updated in years.

**Comment by msaarna** [comment]
Ok, thanks for confirming!
