### ISSUE TITLE
Support all indexed png

### ISSUE THREAD

**Issue by beoran** [7800-devtools/7800basic#8]
Currently 7800basic refuses to include indexed png if they have a byte_depth > 2. however, there are many PNG editors that always save indexed images with byte_depth 8, even if the palette has the right size. I use mtPaint which has this problem. Could such images be accepted as long as the palette size is correct?

**Comment by beoran** [comment]
I made a PR fro discussion #9.

**Comment by msaarna** [comment]
Sure looks good - thanks for the contribution. Merged into master.
